/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ApiService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DevCollabVpc": {
      "type": "sst.aws.Vpc"
    }
    "Frontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "GITHUB_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GROQ_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IMPORT_QUEUE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LIVEBLOCKS_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MEILISEARCH_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MEILISEARCH_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MEILISEARCH_INDEX": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MISSION_QUEUE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PINECONE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PINECONE_INDEX": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PREFERRED_LLM_PROVIDER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "QSTASH_CURRENT_SIGNING_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "QSTASH_NEXT_SIGNING_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "QSTASH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SENDGRID_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TOGETHER_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TaskNotificationsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}

import "sst"
export {}