import { Button, Card, Container, Stack, Text, Title } from "@mantine/core";
import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { IconBrandGoogle, IconGitBranch } from "@tabler/icons-react";
import { withoutAuth } from "../guards/withoutAuth";
import DevCollabIcon from "../components/DevCollabIcon";

const Home: NextPage = () => {
  const handleGithubSignIn = async () => {
    try {
      await signIn("github");
    } catch (error) {
      console.error(error);
    }
  };

  const handleGoogleSignIn = async () => {
    try {
      await signIn("google");
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Dev-Collab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        fluid
        style={{
          minHeight: "100vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "#f8fafc",
        }}
        p="md"
      >
        <Card
          shadow="sm"
          padding="xl"
          radius="md"
          withBorder
          style={{ maxWidth: 400, width: "100%" }}
        >
          <Stack align="center" gap="xl">
            <DevCollabIcon />

            <Title order={2} ta="center" c="dark">
              Welcome to Dev-Collab
            </Title>
            <Text size="md" c="dimmed" ta="center">
              Sign in to collaborate, share, and build amazing projects
              together.
            </Text>
            <Stack w="100%" gap="md">
              <Button
                onClick={handleGithubSignIn}
                leftSection={<IconGitBranch size={20} />}
                variant="filled"
                color="dark"
                radius="md"
                fullWidth
              >
                Sign in with GitHub
              </Button>
              <Button
                onClick={handleGoogleSignIn}
                leftSection={<IconBrandGoogle size={20} />}
                variant="outline"
                color="blue"
                radius="md"
                fullWidth
              >
                Sign in with Google
              </Button>
            </Stack>
            <Text size="sm" c="dimmed" ta="center">
              Don't have an account? Sign up with one click above!
            </Text>
          </Stack>
        </Card>
      </Container>
    </>
  );
};

export const getServerSideProps = withoutAuth(async () => {
  return {
    props: {},
  };
});

export default Home;
