import { Button, Container } from "@mantine/core";
import type { GetServerSideProps, NextPage } from "next";
import { getServerSession } from "next-auth";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { authOptions } from "./api/auth/[...nextauth]";

const Home: NextPage = () => {
  const handleSignIn = async () => {
    try {
      await signIn("github");
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Dev-Collab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        style={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Button variant="filled" onClick={handleSignIn}>
          Sign in with GitHub
        </Button>
      </Container>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerSession(context.req, context.res, authOptions);
  const user = session?.user ?? null;

  if (user) {
    return { redirect: { destination: "/dashboard", permanent: false } };
  }

  return {
    props: {},
  };
};

export default Home;
