import { Button, Container } from "@mantine/core";
import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { IconBrandGoogle, IconGitBranch } from "@tabler/icons-react";
import { withoutAuth } from "../guards/withoutAuth";

const Home: NextPage = () => {
  const handleGithubSignIn = async () => {
    try {
      await signIn("github");
    } catch (error) {
      console.error(error);
    }
  };

  const handleGoogleSignIn = async () => {
    try {
      await signIn("google");
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Dev-Collab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        style={{
          height: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          gap: 10,
        }}
      >
        <Button onClick={handleGithubSignIn} leftSection={<IconGitBranch />}>
          Sign in with GitHub
        </Button>
        <Button onClick={handleGoogleSignIn} leftSection={<IconBrandGoogle />}>
          Sign in with Google
        </Button>
      </Container>
    </>
  );
};

export const getServerSideProps = withoutAuth(async () => {
  return {
    props: {},
  };
});

export default Home;
